services:
  mariadb:
    image: mariadb:10.3
    container_name: Ski-Hotel-DB-01
    restart: no
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: SkiHotelDB
      MARIADB_USER: casualuser
      MARIADB_PASSWORD: casualpass
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d  # SQL files will be added here to be run when the container is created
      - hospitaldb_data_volume:/var/lib/mysql

volumes:
  hospitaldb_data_volume: