services:
  mariadb:
    image: mariadb:10.3
    container_name: SkiHotelDB_01
    restart: no
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: SkiHotelDB
      MARIADB_USER: casualuser
      MARIADB_PASSWORD: casualpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d  # SQL files will be added here to be run when the container is created
      - mariadb_data:/var/lib/mysql
  
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: SkiHotelPSQLDB
    environment:
      POSTGRES_PASSWORD: superpass
      POSTGRES_DB: testDB
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  pgloader:
    image: dimitri/pgloader
    container_name: pgloader
    depends_on:
      mariadb:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
    volumes:
      - ./migrate.load:/mnt/migrate.load
      - ./start.sh:/start.sh
    entrypoint: ["pgloader", "/mnt/migrate.load"]

  simulator:
    build: ./simulator
    container_name: simulator
    depends_on:
      pgloader:
        condition: service_completed_successfully
    command: bash -c "python3 post_migration.py && python3 simulator.py"

volumes:
  mariadb_data:
  timescaledb_data:

  # psql-runner:
  #   image: postgres:15
  #   container_name: psql_runner
  #   depends_on:
  #     pgloader:
  #       condition: service_completed_successfully
  #   volumes:
  #     - ./post_migration:/scripts  # Your custom SQL files
  #   entrypoint: ["/bin/bash", "-c"]
  #   command: >
  #     "
  #     echo 'Waiting for TimescaleDB to be ready...';
  #     until pg_isready -h timescaledb -U postgres; do sleep 2; done;
  #     echo 'Running post-migration SQL...';
  #     psql -h timescaledb -U postgres -d testDB -f /scripts/post_migration.sql;
  #     echo 'Post-migration SQL done.';
  #     "
  #   environment:
  #     PGPASSWORD: superpass